replicaCount: 1

image:
  registry: ms.azurecr.io
  repository: hello-world-node-pg
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 9
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 90

tenantName: default
keyVaultName: default
keyVaultTenant: default
clientId: default
domainName: foo.bar
certificateName: default