apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.tenantName }}.{{ .Values.domainName }}
    secretName: tls
  rules:
  - host: {{ .Values.tenantName }}.{{ .Values.domainName }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: {{ .Chart.Name }}
            port: 
              number: {{ .Values.service.port }}