apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault
spec:
  provider: azure
  secretObjects:
  - secretName: postgres-connection-string
    type: Opaque
    data:
    - objectName: postgres-connection-string-alias
      key: value
  - secretName: tls
    type: kubernetes.io/tls
    data: 
    - objectName: {{ .Values.certificateName }}
      key: tls.key
    - objectName: {{ .Values.certificateName }}
      key: tls.crt
  parameters:
    clientID: {{ .Values.clientId }}
    keyvaultName: {{ .Values.keyVaultName }}
    tenantId: {{ .Values.keyVaultTenant }}
    objects:  |
      array:
        - |
          objectName: {{ .Values.tenantName }}-postgres-connection-string
          objectAlias: postgres-connection-string-alias
          objectType: secret
        - |
          objectName: {{ .Values.certificateName }}
          objectType: secret
          